version: '3.8'
services:
  web-api:
    build:
      context: /home/dev/homework_12/
      dockerfile: Dockerfile
      args:
        APP_ENV: 'dev'
    ports:
      - "8080:8080"
    entrypoint: >
      sh -c "git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git
      && cd App42PaaS-Java-MySQL-Sample
      && start-my-app-command"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"