version: '3.8'
services:
  web-api:
    build:
      context: /home/dev/homework_12/
      command: >
        sh -c "git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git
        && start-my-app-command"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"